apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-service
  namespace: microservices
spec:
  hosts:
    - "*"
  gateways:
    - microservices-gateway
  http:
    - match:
        - uri:
            prefix: /api/orders
      route:
        - destination:
            host: order-service
            subset: v1
      timeout: 3s
      retries:
        attempts: 5
        perTryTimeout: 1s
        retryOn: 5xx,reset,connect-failure,refused-stream,retriable-4xx