apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-v1
  namespace: microservices
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: v1
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
        - name: order-service
          image: acristio1767868439.azurecr.io/order-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVICE_VERSION
              value: "v1"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/orders/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/orders/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5