apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-v2
  namespace: microservices
  labels:
    app: order-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
      version: v2
  template:
    metadata:
      labels:
        app: order-service
        version: v2
    spec:
      containers:
        - name: order-service
          image: acristio1767868439.azurecr.io/order-service:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVICE_VERSION
              value: "v2"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"